name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (Node.js example)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install

      # Step 3: Run tests
      - name: Run Tests
        run: npm test

      # Step 4: Deploy
      - name: Deploy
        run: npm run deploy

















