name: CI/CD Pipeline
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover

      - name: Commit and push changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This job depends on the test job
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only run on push to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here
          # For example, using SSH to deploy to a server
          # ssh user@your-server "cd /path/to/app && git pull && npm install && npm run start"
