name: CI/CD Pipeline - Development, Testing, and Deployment

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  # Job to set up the environment and run tests
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Python environment (for a Python project)
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # Install dependencies for Python
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run Python tests (using pytest for Python)
    - name: Run Python Tests
      run: |
        pip install pytest
        pytest

    # Set up Node.js (for JavaScript code)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install dependencies for JavaScript
    - name: Install Node.js dependencies
      run: npm install

    # Run JavaScript tests (using Jest, Mocha, etc.)
    - name: Run JavaScript Tests
      run: npm test

  # Job to deploy the application
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Ensure that tests pass before deployment

    steps:
    - name: Checkout Repository (only once for deployment)
      uses: actions/checkout@v3

    # Install dependencies for deployment (only necessary if deployment needs a specific environment)
    - name: Install Python and Node.js dependencies for deployment
      run: |
        pip install -r requirements.txt  # Python dependencies
        npm install  # Node.js dependencies

    # Deploy to Development Environment (or production, depending on your branch)
    - name: Deploy to Development Environment
      run: |
        echo "Deploying to Development Environment..."
        # Add your deployment script or command here, e.g., SSH, Docker, etc.

















