name: CI/CD Pipeline

# Trigger the workflow on push or pull_request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to set up environment (Dev)
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  # Job to run tests (Test)
  test:
    runs-on: ubuntu-latest
    needs: dev  # Ensure that 'dev' job is completed before starting test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Job to deploy the application (Deploy)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure that 'test' job is completed before deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Example of deployment step (modify to your actual deployment process)
      - name: Deploy to production
        run: |
          echo "Deploying application..."
          # Replace this with your actual deployment command, e.g., AWS CLI, FTP, etc.
          # For example, using AWS CLI:
          # aws s3 sync ./build s3://your-bucket-name

