# This workflow will install Python dependencies, run tests, lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Application CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


  test:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Run tests
        run: |
         pytest  # Run tests using pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This job depends on the test job
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Only deploy on push to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          echo "Deploying to Render..."
          curl -X POST https://api.render.com/deploy/some-service-id \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
        
